search: compatibility tweaks

diff --git a/search b/search
--- a/search
+++ b/search
@@ -3,30 +3,29 @@
 # Searches for everywhere some pesky command could be hiding.
 
 if [ $# -ne 1 ]; then
-    echo "Usage: $0 command" >&2
-    exit 1
+  printf "Usage: %s command\n" "$0" >&2
+  exit 1
 fi
 
 for i in \
-        "which" \
-        "apt-cache search" \
-        "gem search" \
-        "gem search -r" \
-        "cabal list --simple-output" \
-        "pip search" \
-        "pip3 search" \
-        "port search" \
-        "/usr/lib/command-not-found --no-failure-msg" \
-        ; do
-    # Get the first word of the command to check for existence.
-    cmd=${i%% *}
-    which ${cmd} &>/dev/null
-    if [ $? -eq 0 ]; then
-        $i "$1" 2>&1 | \
-            while read line; do
-                echo "[$i]: ${line}"
-            done
-    else
-        echo "${cmd} not found, skipping." >&2
-    fi
+      "which" \
+      "apt-cache search" \
+      "gem search" \
+      "gem search -r" \
+      "cabal list --simple-output" \
+      "pip search" \
+      "pip3 search" \
+      "port search" \
+      "/usr/lib/command-not-found --no-failure-msg" \
+      ; do
+  # Get the first word of the command to check for existence.
+  cmd=${i%% *}
+  if which ${cmd} &>/dev/null; then
+    $i "$1" 2>&1 | \
+      while read line; do
+        printf "[%s]: %s\n" "$i" "${line}"
+      done
+  else
+    printf "%s not found, skipping.\n" "${cmd}" >&2
+  fi
 done
