wim: compatibility tweaks

diff --git a/wim b/wim
--- a/wim
+++ b/wim
@@ -3,13 +3,13 @@
 # Lazy vim `which foo`.
 
 if [ $# -gt 0 ]; then
-    # Cope with the fact that $1 may be a zsh/bash macro.
-    ITEM=`sh -c "which $1"`
-    if [ -z "${ITEM}" ]; then
-        echo "$1 not found" >&2
-        exit 1
-    fi
-    vim "${ITEM}"
+  # Cope with the fact that $1 may be a zsh/bash macro.
+  ITEM=$(sh -c "which $1")
+  if [ -z "${ITEM}" ]; then
+    printf "%s not found\n" "$1" >&2
+    exit 1
+  fi
+  vim "${ITEM}"
 else
-    vim
+  vim
 fi
